server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://ip:3306/udp?characterEncoding=UTF-8
    username: udp
    password: udp2016
    driver-class-name: com.mysql.jdbc.Driver
